### ISSUE TITLE
std::map member variables should be marked as const if they never change

### ISSUE THREAD

**Issue by korydraughn** [irods/irods_client_rest_cpp#1]
Given that these maps never change, they should be marked `const`. This would also require that you use `std::map::at instead` of `std::map::operator[]`.

These could possibly be marked as `static` as well.

https://github.com/jasoncoposky/irods_client_rest_cpp/blob/15d367c05e387743d45ed8eb4d5fe9c7c34e4a9f/irods_specific_implementation/irods_rest_list_api_implementation.h#L136

https://github.com/jasoncoposky/irods_client_rest_cpp/blob/15d367c05e387743d45ed8eb4d5fe9c7c34e4a9f/irods_specific_implementation/irods_rest_list_api_implementation.h#L145

**Comment by jasoncoposky** [comment]
resolved by commit bdf398e
