### ISSUE TITLE
/list endpoint for collection not providing size information for the files in that collection

### ISSUE THREAD

**Issue by hchendow** [irods/irods_client_rest_cpp#113]
It would be nice to be able to have the /list endpoint provide the byte size for each of the file in the collection like the /list endpoint does for a data object so that we can use that information to get all of the data objects in that collection with the /stream endpoint.

**Comment by trel** [comment]
need to honor `stat=1`, `metadata=1`, and `permissions=1` (and `0`), perhaps as well as 'true/false'.

**Comment by darwinjob** [comment]
>like the /list endpoint does for a data object
Could you please share how? I mean how can I get the size of an object using the API?

**Comment by hchendow** [comment]
You have to query a data object for the /list endpoint and then you have to set stat=true/false. I don't think you'll need metadata and permissions in the request so you can set them to 0 and false respectively.

**Comment by alanking** [comment]
1 is now honored in the list endpoint. We are going to leave this open for now so that we can make sure this is fully addressed.
