### ISSUE TITLE
Support Metadata

### ISSUE THREAD

**Issue by kript** [irods/irods_client_rest_cpp#118]
Hi folks,

Does this support metadata? I didn't used to and the README implies it still doesn't, so I thought I'd check and see what the roadmap was for when it would.

cheers

John

**Comment by trel** [comment]
in progress...  https://github.com/irods/irods_client_rest_cpp/pull/115

**Comment by phdavis1027** [comment]
It's been supported!

**Comment by alanking** [comment]
Reopening for cherry-pick to 4-2-stable

**Comment by alanking** [comment]
Closing because the 4-2-stable branch will no longer receive updates. This application should not be installed alongside the iRODS server, which would require the `irods-runtime` package versions to match.
