### ISSUE TITLE
Support delete and rename

### ISSUE THREAD

**Issue by phdavis1027** [irods/irods_client_rest_cpp#123]
The REST API should be able to delete or rename data objects and collections.

**Comment by phdavis1027** [comment]
Addressed by #116

**Comment by korydraughn** [comment]
@alanking Please add checkboxes for main and 4-2-stable.

**Comment by alanking** [comment]
Done.

Didn't even know there was a 4-2-stable branch in this repo.

**Comment by trel** [comment]
Maybe we don't need a 4-2-stable?   It's just a client...

**Comment by korydraughn** [comment]
True. I can't remember why we introduced a 4-2-stable branch.

**Comment by alanking** [comment]
Closing because the 4-2-stable branch will no longer receive updates. This application should not be installed alongside the iRODS server, which would require the `irods-runtime` package versions to match.
