### ISSUE TITLE
/query should make all of its input uppercase if case_sensitive=0

### ISSUE THREAD

**Issue by phdavis1027** [irods/irods_client_rest_cpp#124]
genQuery implements case-insensitivity by requiring that its input  be all uppercase. The /query endpoint should make sure that any input given to it is made uppercase before passing it to the API calls.

**Comment by alanking** [comment]
Closing because the 4-2-stable branch will no longer receive updates. This application should not be installed alongside the iRODS server, which would require the `irods-runtime` package versions to match.
