### ISSUE TITLE
Refactor iteration in /list

### ISSUE THREAD

**Issue by phdavis1027** [irods/irods_client_rest_cpp#128]
The "recursive" flag on the /list endpoint repeats the same codeblock, to handle both the recursive and non-recursive collection iterators. Ways of making this less redundant could be:
- Creating either a recursive_collection iterator or a collect_iterator depending on the flag, so that there's only over one block of code that loops.
- Retaining the two loops, but pulling the bodies into a separate function to increase maintainability.

**Comment by trel** [comment]
Either seems fine with me - option 2 is probably easier to understand for the next reader.

**Comment by alanking** [comment]
Went with a solution that more resembles option 1 using `std::variant` and `std::visit` to iterate over the results without worrying about which type of collection iterator is being used.
