### ISSUE TITLE
where should this be run?

### ISSUE THREAD

**Issue by kript** [irods/irods_client_rest_cpp#13]
My apologies for the basic question, but reading the getting started notes it isn't clear to me if this assumes an installation on an existing Provider, or if it can/should go over the network to talk to one like a 'normal' client?

**Comment by jasoncoposky** [comment]
@kript The REST API assumes that it is run along an existing iRODS server with an authenticated rodsadmin iRODS environment available.  It will also use one port per endpoint and expects an nginx reverse proxy to route all the paths through port 80.
