### ISSUE TITLE
Add support for other authentication methods (PAM)

### ISSUE THREAD

**Issue by alanking** [irods/irods_client_rest_cpp#131]
Currently, only native authentication is supported. We should add support for other authentication plugins which exist in the server. At the time of writing, this would apply only to `pam_password` for 4.3.0, but `pam_interactive` will certainly be a good match for this client.

**Comment by trel** [comment]
This will not be implemented in this repository.

Please see the new HTTP API:

https://github.com/irods/irods_client_http_api
