### ISSUE TITLE
Services terminate with uncaught exceptions

### ISSUE THREAD

**Issue by alanking** [irods/irods_client_rest_cpp#137]
There are a variety of things which can cause this, but here are some that I have observed:

- Failure to connect to iRODS server
- Failure to parse JSON configuration
- Unexpected JSON structures in configuration

We just need to catch these exceptions and handle them in the appropriate places to prevent program termination as these are meant to be long-running processes.

**Comment by boydwilson** [comment]
Will do as we run into them, thanks.

**Comment by trel** [comment]
This will not be addressed in this repository.

Please see the new HTTP API:

https://github.com/irods/irods_client_http_api
