### ISSUE TITLE
Investigate remote users and user names with embedded zone names

### ISSUE THREAD

**Issue by alanking** [irods/irods_client_rest_cpp#138]
https://github.com/irods/irods_client_rest_cpp/blob/0f1c0c28efbae6cc3eb6d2289a442124653e5081/irods_specific_implementation/indexed_connection_pool_with_expiry.hpp#L53-L69

The `connection_handle` constructors used by connection pools seem to assume that the client and proxy users are in the same zone. We should investigate whether this causes problems for federation and/or remote users.

Here is where the connection is being made:
https://github.com/irods/irods_client_rest_cpp/blob/0f1c0c28efbae6cc3eb6d2289a442124653e5081/irods_specific_implementation/indexed_connection_pool_with_expiry.hpp#L211-L213

**Comment by trel** [comment]
This will not be addressed in this repository.

Please see the new HTTP API:

https://github.com/irods/irods_client_http_api
