### ISSUE TITLE
Supported Versions

### ISSUE THREAD

**Issue by kript** [irods/irods_client_rest_cpp#14]
Hi folks,

I understand this is under active development, but it would be good to know which version(s) it has been tested with, and/or which version is assumed when installing, and or which versions should work with it. 

My assumption is that it works with any 4.2.x version, but that may not be correct or misremembered from the talk in Dedember...

**Comment by trel** [comment]
We have not tested it backwards... but my assumption is that you are correct
 - 4.2.x at minimum
 - probably late-model 4.1.x

**Comment by trel** [comment]
@korydraughn I don't remember... did we need to add anything to the iRODS server for this to be functional?    Is 4.2.0 a viable minimum version to put in the README?

**Comment by korydraughn** [comment]
It uses a lot of the new libs, so I'd use the earliest version number mentioned on the irods_api_examples repo's README.

**Comment by trel** [comment]
that appears to be 4.2.5

https://github.com/irods/irods_library_examples

**Comment by trel** [comment]
related... https://github.com/irods/irods_client_rest_cpp/commit/231e69e488bfefc03192040bc50d1b9b69e1c1a9#commitcomment-56921702

**Comment by trel** [comment]
Set it to 4.2.0.

It's not about the libraries used, it's about the iRODS protocol compatibility, and the `resc_name` to `resc_id` conversion in 4.2.0.
