### ISSUE TITLE
/list endpoint needs to provide mapping for all permission levels

### ISSUE THREAD

**Issue by korydraughn** [irods/irods_client_rest_cpp#157]
https://github.com/irods/irods_client_rest_cpp/blob/8500d64dfd4846b98bd091156a4d10c7bc5347e9/irods_specific_implementation/irods_rest_list_api_implementation.h#L196-L201

**Comment by trel** [comment]
This will not be implemented in this repository.

Please see the new HTTP API:

https://github.com/irods/irods_client_http_api
