### ISSUE TITLE
/stream poor parallel performance 

### ISSUE THREAD

**Issue by darwinjob** [irods/irods_client_rest_cpp#160]
Hi
We have this test OpenSeadragon viewer deployed at 
https://staging.ns9999k.webs.sigma2.no/dmitri-tests/index.html

If you're patient enough (20-30 sec) you will see this:
<img width="1071" alt="image" src="https://user-images.githubusercontent.com/358762/192323487-c698b577-e9c8-45fa-9803-09c7a35ca91b.png">

The viewer gets the data thru iRODS REST API. The data are PNG tiles. By checking the Network tab you'll see that it takes 20-30 seconds to download 10 - 50 kb tile:
<img width="1125" alt="image" src="https://user-images.githubusercontent.com/358762/192326352-90ffbba5-c92c-4da1-8cd6-acd716821066.png">

I also performed a curl test by downloading 30 tiles, the command (-Z means parallel):
`curl -Z 'https://api.nesys.sigma2.no/irods-rest/0.9.1/stream?path=/NESYS/projects/tgArcSwe_atlas/F1__AD_24_1_7_F3/Beta_amyloid_immunostain_F1/pyramids/AD_24_1_7_F3_16_05_12_a.tif/AD_24_1_7_F3_16_05_12_a.tif_files/15/14_[0-29].png&count=10000000' -o '#1.png' -H 'Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXUyJ9.eyJhdWQiOiJhdWRpZW5jZV9jbGFpbSIsImlhdCI6MTY1NzU2MDMxMiwiaXNzIjoiaXNzdWVfY2xhaW0iLCJuYmYiOjE2NTc1NjAzMTIsInN1YiI6InN1YmplY3RfY2xhaW0iLCJ1c2VyX25hbWUiOiJyb2RzIn0.yB_l6e-NAxjAa4yHF3FeDD2vO-a3HS4h92Qohnq6b7Y'`

The output:

`[1/30]: https://api.nesys.sigma2.no/irods-rest/0.9.1/stream?path=/NESYS/projects/tgArcSwe_atlas/F1__AD_24_1_7_F3/Beta_amyloid_immunostain_F1/pyramids/AD_24_1_7_F3_16_05_12_a.tif/AD_24_1_7_F3_16_05_12_a.tif_files/15/14_0.png&count=10000000 --> 0.png
...
[30/30]: https://api.nesys.sigma2.no/irods-rest/0.9.1/stream?path=/NESYS/projects/tgArcSwe_atlas/F1__AD_24_1_7_F3/Beta_amyloid_immunostain_F1/pyramids/AD_24_1_7_F3_16_05_12_a.tif/AD_24_1_7_F3_16_05_12_a.tif_files/15/14_29.png&count=10000000 --> 29.png
DL% UL%  Dled  Uled  Xfers  Live   Qd Total     Current  Left    Speed
100 --  2787k     0    30     0     0  0:00:08  0:00:27 --:--:--  333k`

So as you can see - 27 sec.

Is this expected timing? I'm asking because the same dataset looks like this on our old outdated system:
http://cmbn-navigator.uio.no/navigator/openseadragon/index.html?id=14606

**Comment by korydraughn** [comment]
We haven't done any performance testing for the REST API. With this, we now have a baseline for the /stream endpoint.

There are definitely things we can do to improve the situation. One improvement we're looking at is the handling of iRODS connections. You can follow that work at https://github.com/irods/irods/pull/6593.

What happens if you bump the number of threads up for the /stream endpoint? It defaults to 4.

**Comment by trel** [comment]
A quick click / inspect suggests there were 40-50 pngs/tiles per reload on the old system.

**Comment by darwinjob** [comment]
Hi
I've tried to simulate the same 30 parallel requests using Jargon. The timing is about the same 😟 which might mean that the bottleneck is not the REST API but our iRODS setup itself (or iRODS in general).

```package irods_test;

import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

import org.irods.jargon.core.connection.AuthScheme;
import org.irods.jargon.core.connection.ClientServerNegotiationPolicy.SslNegotiationPolicy;
import org.irods.jargon.core.connection.IRODSAccount;
import org.irods.jargon.core.connection.SettableJargonPropertiesMBean;
import org.irods.jargon.core.exception.JargonException;
import org.irods.jargon.core.pub.DataTransferOperations;
import org.irods.jargon.core.pub.IRODSAccessObjectFactory;
import org.irods.jargon.core.pub.IRODSFileSystem;

public class IRODStest {

	public static void main(String[] args) throws JargonException {

		IRODSAccount irodsAccount = IRODSAccount.instance(XXX);
		irodsAccount.setAuthenticationScheme(AuthScheme.STANDARD);

		IRODSFileSystem irodsFileSystem = IRODSFileSystem.instance();

		SettableJargonPropertiesMBean settableJargonProperties = (SettableJargonPropertiesMBean) irodsFileSystem
				.getJargonProperties();
		settableJargonProperties.setNegotiationPolicy(SslNegotiationPolicy.CS_NEG_REQUIRE);
		irodsFileSystem.getIrodsSession().setJargonProperties(settableJargonProperties);

		IRODSAccessObjectFactory accessObjectFactory = irodsFileSystem.getIRODSAccessObjectFactory();

		DataTransferOperations dto = accessObjectFactory.getDataTransferOperations(irodsAccount);

		ExecutorService executor = Executors.newFixedThreadPool(30);

		for (int i = 0; i < 30; i++) {
			executor.execute(new DownloadTile(i, dto));
		}

		executor.shutdown();
	}
}

class DownloadTile implements Runnable {

	int i;
	DataTransferOperations dto;

	public DownloadTile(int i, DataTransferOperations dto) {
		this.i = i;
		this.dto = dto;
	}

	public void run() {
		try {
			long t = System.currentTimeMillis();
			System.out.println("14_" + i + ".png started at " + t);

			String p = "/NESYS/projects/tgArcSwe_atlas/F1__AD_24_1_7_F3/Beta_amyloid_immunostain_F1/pyramids/AD_24_1_7_F3_16_05_12_a.tif/AD_24_1_7_F3_16_05_12_a.tif_files/15/14_"
					+ i + ".png";
			dto.getOperation(p, i + ".png", "", null, null);

			System.out.println("14_" + i  + ".png took " + (System.currentTimeMillis() - t)/1000f + " sec");
		} catch (Exception err) {
			err.printStackTrace();
		}
	}
}
```

The output:
```
14_0.png started at 1666035000651
14_1.png started at 1666035000651
14_2.png started at 1666035000651
14_3.png started at 1666035000651
14_4.png started at 1666035000651
14_5.png started at 1666035000651
14_6.png started at 1666035000652
14_7.png started at 1666035000652
14_8.png started at 1666035000652
14_9.png started at 1666035000652
14_10.png started at 1666035000660
14_11.png started at 1666035000660
14_12.png started at 1666035000660
14_13.png started at 1666035000661
14_14.png started at 1666035000661
14_15.png started at 1666035000661
14_16.png started at 1666035000661
14_17.png started at 1666035000661
14_18.png started at 1666035000661
14_19.png started at 1666035000661
14_20.png started at 1666035000662
14_21.png started at 1666035000662
14_22.png started at 1666035000662
14_23.png started at 1666035000662
14_24.png started at 1666035000662
14_25.png started at 1666035000662
14_26.png started at 1666035000663
14_27.png started at 1666035000663
14_28.png started at 1666035000663
14_29.png started at 1666035000663
14_3.png took 10.511 sec
14_6.png took 17.508 sec
14_8.png took 19.807 sec
14_2.png took 20.008 sec
14_0.png took 20.708 sec
14_18.png took 21.098 sec
14_13.png took 21.1 sec
14_10.png took 21.101 sec
14_14.png took 21.712 sec
14_4.png took 22.323 sec
14_20.png took 22.397 sec
14_1.png took 24.339 sec
14_15.png took 24.603 sec
14_21.png took 24.712 sec
14_9.png took 25.006 sec
14_29.png took 25.499 sec
14_7.png took 25.706 sec
14_12.png took 25.8 sec
14_27.png took 25.911 sec
14_17.png took 26.001 sec
14_16.png took 26.099 sec
14_5.png took 26.222 sec
14_19.png took 26.612 sec
14_11.png took 27.498 sec
14_23.png took 27.498 sec
14_22.png took 27.599 sec
14_26.png took 27.795 sec
14_25.png took 27.899 sec
14_24.png took 27.991 sec
14_28.png took 28.09 sec
```
I hope this might help somehow.

**Comment by trel** [comment]
That is interesting... and yes, it suggests REST may not be to blame.

Can you please time grabbing any one of those files with `iget`?

And then the same 30 files with `parallel` and `iget`?

**Comment by darwinjob** [comment]
```
>time seq 1 30 | parallel iget /NESYS/projects/tgArcSwe_atlas/F1__AD_24_1_7_F3/Beta_amyloid_immunostain_F1/pyramids/AD_24_1_7_F3__a.tif/AD_24_1_7_F3_16_05_12_a.tif_files/15/14_{}.png
real	0m19.162s
user	0m1.455s
sys	0m0.418s
```

So this is slow iRODS. After we added more resources to iRODS server and did some Postgres optimization we got much better results:
```
real	0m2.729s
user	0m1.917s
sys	0m0.593s
```
Now we have 4cpu/8GB for the iRODS server and 4cpu/4GB for the DB. Increasing these values further didn't improve the performance. 

Jargon test is also much better:

```
14_0.png took 0.788 sec
14_6.png took 0.788 sec
14_2.png took 0.788 sec
14_3.png took 0.793 sec
14_4.png took 0.796 sec
14_1.png took 0.881 sec
14_5.png took 0.9 sec
14_8.png took 0.92 sec
14_12.png took 0.926 sec
14_10.png took 0.945 sec
14_7.png took 0.96 sec
14_14.png took 0.968 sec
14_17.png took 0.969 sec
14_9.png took 0.979 sec
14_13.png took 0.977 sec
14_15.png took 1.01 sec
14_18.png took 1.01 sec
14_25.png took 1.009 sec
14_23.png took 1.01 sec
14_20.png took 1.01 sec
14_19.png took 1.014 sec
14_24.png took 1.025 sec
14_11.png took 1.029 sec
14_16.png took 1.028 sec
14_29.png took 1.033 sec
14_27.png took 1.053 sec
14_26.png took 1.068 sec
14_28.png took 1.08 sec
14_21.png took 1.087 sec
14_22.png took 1.092 sec

```

The curl command is pretty fast now:
```
DL% UL%  Dled  Uled  Xfers  Live   Qd Total     Current  Left    Speed
100 --  2787k     0    30     0     0  0:00:05  0:00:05 --:--:--  547k
```

But in the browser it still takes around 10 seconds per tile. Which is slow.
<img width="1125" alt="image" src="https://user-images.githubusercontent.com/358762/197348737-df701003-35dd-4bd9-a241-cd3e34ad6127.png">

I'm a bit lost: how come curl is fast but the browser is times slower? Because of OPTIONS call???

**Comment by trel** [comment]
Both curl and browser are hitting the same REST API URL?   And getting wildly different results?   That's very strange indeed.

**Comment by darwinjob** [comment]
Yes, the same API (we only have one 🙂) The data is slightly different - different set of tiles. But all the tiles are 256x256 PNG images.

**Comment by trel** [comment]
Curious.

Any other clients you can point at it for comparison?   Different browsers?

**Comment by darwinjob** [comment]
Hi
The timing for loading the initial view on 1920x1080 screen is approximately the same on Safari (Mac), Firefox (Mac, Win), Edge (Win) and GC (Win). The screenshot above might be a bit misleading because it displays a time point when a user already navigated away from the initial view. Anyway, the observation is the following:
<img width="954" alt="image" src="https://user-images.githubusercontent.com/358762/202915109-ac6cdfde-3dd7-4411-a51a-b5a4e7a3ca1f.png">
 
As you can see the most of the time it's in a waiting phase, not downloading. Can this be related to Pistache framework?

**Comment by trel** [comment]
The overhead of the REST API will be demonstrated by the difference between a single `iget` call directly to iRODS and hitting the `stream` endpoint of the REST API.

Agreed, 5 seconds (5150.4ms in the screenshot) is still a surprisingly long time.

How far away (latency) is the REST API from the iRODS server?  Is there a chance that the DNS (or something else in the networking) is somehow sitting idle, waiting for a timeout somewhere?  We have not seen this delay ourselves with local testing.

**Comment by darwinjob** [comment]
> The overhead of the REST API will be demonstrated by the difference between a single iget call directly to iRODS and hitting the stream endpoint of the REST API.

According to our tests getting a single file:
iget gives 0.22-0.24s while curl gives 0.25-0.33s.
Tested with 5 attempts.

The issue truly shows up with the parallel transfer. 

Curl -Z, 30 files, from inside the container:
```
$ time ./testspeed.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   240  100   240    0     0    644      0 --:--:-- --:--:-- --:--:--   645
DL% UL%  Dled  Uled  Xfers  Live   Qd Total     Current  Left    Speed
100 --  2787k     0    30     0     0  0:00:05  0:00:05 --:--:--  502k
real	0m5.946s
user	0m0.100s
sys	0m0.132s

```

iget parallel , same 30 files, from inside the container:
```
real	0m1.322s
user	0m2.166s
sys	0m0.809s

```
Jargon parallel (threads) requests of the same 30 files are around 1 sec too.
So I suspect this is about the REST API app. Sorry :)

**Comment by trel** [comment]
> What happens if you bump the number of threads up for the /stream endpoint? It defaults to 4.

Is this still set to 4 for this `curl -Z` test?    Asking 4 for 30 is a 7x pileup on each.

**Comment by darwinjob** [comment]
We set it to 8 - it seems it gives us a little performance boost.

> The C++ REST API does not support parallel transfer yet, so the speed of a transfer will depend on the size of the file. That is a known issue and will be worked on in a future release of the API.

https://github.com/irods/irods_client_library_rirods/issues/9#issuecomment-1329531660

Is this relevant for our case?

**Comment by trel** [comment]
No, iRODS 'parallel transfer' is about splitting a single file into many smaller parts (similar to multipartUpload for S3)...

You have sent 30 concurrent different files at the same time.

**Comment by trel** [comment]
@darwinjob any news / updates?

**Comment by adilhasan** [comment]
Hello Terrell, sorry for the long delay in getting back to you on this. Kory suggested to move forwards to a new version of irods c++ API, but for that we needed to upgrade iRODS to 4.3. We ran into problems trying to restart iRODS as it seemed that there was something that wanted to use systemd. We can't use that on our Kubernetes cluster. Kory also suggested that we try to specify a fully qualified name for the host, but we can't do that on our Kubernetes cluster either (each host gets a local ip address and the nginx reverse proxy maps the requests to the correct host). So, we're a bit stuck at the moment.

**Comment by trel** [comment]
@adilhasan Are you in the correct issue here?

Not sure about the upgrade either...
> This REST API requires an iRODS Server v4.2.0 or greater.

**Comment by korydraughn** [comment]
Created #183 to address adding support for parallel transfer.

**Comment by korydraughn** [comment]
We can leave this open untile #183 is complete.

**Comment by trel** [comment]
This work has been incorporated / implemented in the new HTTP API.

https://github.com/irods/irods_client_http_api
