### ISSUE TITLE
Turn of URL globbing in README metadata example

### ISSUE THREAD

**Issue by MartinSchobben** [irods/irods_client_rest_cpp#161]
The README example for the API's `/metadata` endpoint uses the reserved symbols [] and {}. Either globbing should be turned off:

`curl -X POST -H "Authorization: ${TOKEN}" "http://localhost/irods-rest/0.9.2/metadata?cmds=${CMDS}" -g`

Or the the symbols should be URL encoded. The current example is invalid.

I also wonder whether the JSON object should be included in the request body (with the `-d` flag) instead of the header.

https://everything.curl.dev/cmdline/globbing#output-variables-for-globbing

**Comment by korydraughn** [comment]
Very good point. We'll investigate.

**Comment by alanking** [comment]
I found that this worked for me:
```
curl -X POST \
-H "Authorization: ${TOKEN}" \
-H "Content-Type: application/json" \
--data '
{
  "entity_name": "/tempZone/home/rods/dir1",
  "entity_type": "collection",
  "operations": [
    {
      "operation": "add",
      "attribute": "attr",
      "value": "val",
      "units": "u" 
    }
  ]
}' \
http://localhost/irods-rest/0.9.2/metadata
```
Would this be a good example to use instead?

**Comment by MartinSchobben** [comment]
Great, that works!
