### ISSUE TITLE
Remove dependence on `$HOME` environment variable

### ISSUE THREAD

**Issue by alanking** [irods/irods_client_rest_cpp#164]
Because of `obfGetPw` and other functions of that familiy, we are required to set `$HOME` and create a `.irods` directory in which to save the `.irodsA` file required by the iRODS authentication plugins.

We should move this to `/etc/irods_client_rest_cpp` along with all of the other configuration so that it is securely stored and more hands-free.

**Comment by trel** [comment]
The workaround until this is fixed is to edit the init.d script to export `$HOME` manually...

https://github.com/irods/irods_client_rest_cpp/blob/987a1d077e6c88ab24a86d6710ba8196307ff35d/packaging/irods_client_rest_cpp#L54-L60

As this is not generic (b/c it's a workaround), you may need to tweak the actual location of `HOME=` for your deployment environment:

```diff
start_irods_client_rest_cpp() {
+   export HOME="/root"
    for API in `ls /usr/sbin/$PREFIX*`
    do
        ${API}&
    done
    mkdir -p "${HOME}"/.irods
}
```

**Comment by alanking** [comment]
Discovered that setting `$HOME` to `/var/lib/irods` as part of this workaround can cause major problems.

The working theory is that the `.irodsA` file in use by the service account gets overwritten by the REST client (i.e. root) and causes the server to lock up. I believe it's a timing issue, but it's not clear when the problem occurs. In any case, the REST client should definitely not be writing .irodsA files in `/var/lib/irods/.irods`. This used to work because the REST services were being run by the iRODS service account. This is no longer the case, so writing the authentication file there is now a problem.
