### ISSUE TITLE
Add `imkdir`-like capability

### ISSUE THREAD

**Issue by alanking** [irods/irods_client_rest_cpp#165]
An operation similar to `imkdir` should be possible via the `/logicalpath` endpoint. Initial approach will use the `POST` operation with a parameter to indicate that a collection is being created.

`irmdir` should be a matter of allowing removal of empty collections via `DELETE` without the recursive flag.

**Comment by trel** [comment]
do we already support the equivalent of `rm -r` / `irm -r`?    so `irmdir` is new/different/safer?

**Comment by alanking** [comment]
Yes, `irm`-like behavior is possible via `DELETE` on `/logicalpath`. `&recursive=1` is required for collections, empty or not. I think `irmdir`-like behavior would just be not requiring `&recursive=1` for empty collections. Seems safe enough to me. Not sure if it adds a lot of value, but it was easy enough to implement.

**Comment by trel** [comment]
Okay.  Maybe we hold off introducing rmdir…

Fewer ways for people to hold things…?

**Comment by trel** [comment]
And less to document

**Comment by alanking** [comment]
Okay. I'll leave off `rmdir`-like functionality for now.
