### ISSUE TITLE
`/logicalpath`: Investigate default behavior for `POST`

### ISSUE THREAD

**Issue by alanking** [irods/irods_client_rest_cpp#168]
The default behavior for `POST` is currently a no-op. We should decide what this should do by default.

Initial thought from me was something like `itouch`, but it only allows creating new data objects.

**Comment by trel** [comment]
a default `POST` for `/logicalpath` does seem to be a 'touch' which would create a new data object

OR(?)

update the modify_time of an existing data object (hrm... replica?)

**Comment by trel** [comment]
This will not be addressed in this repository.

Please see the new HTTP API:

https://github.com/irods/irods_client_http_api
