### ISSUE TITLE
Investigate performance delta with `rc_switch_user` API endpoint

### ISSUE THREAD

**Issue by korydraughn** [irods/irods_client_rest_cpp#172]
See the following:
- https://github.com/irods/irods/blob/c3c62ad4cfe8064bcc1475839cc79f362d0e1caa/lib/core/include/irods/library_features.h
- https://github.com/irods/irods/blob/c3c62ad4cfe8064bcc1475839cc79f362d0e1caa/lib/api/include/irods/switch_user.h

**Comment by trel** [comment]
This will not be implemented in this repository.

Please see the new HTTP API:

https://github.com/irods/irods_client_http_api
