### ISSUE TITLE
/stream endpoint should accept 0 or 1 for truncate parameter

### ISSUE THREAD

**Issue by korydraughn** [irods/irods_client_rest_cpp#176]
https://github.com/irods/irods_client_rest_cpp/blob/8fb9c32735d99112d2abe153bee0fe87e25b0f0e/irods_specific_implementation/irods_rest_stream_put_api_implementation.h#L96-L99

**Comment by trel** [comment]
since we're not at 1.0.... let's standardize on 0 and 1 for all these flags.  no more true/false.

not worried about backwards compatibility as this is the first or second use of /stream we've tried - there should be no existing code out there.

**Comment by trel** [comment]
This will not be implemented in this repository.

Please see the new HTTP API:

https://github.com/irods/irods_client_http_api
