### ISSUE TITLE
/query does not set a default limit correctly

### ISSUE THREAD

**Issue by trel** [irods/irods_client_rest_cpp#182]
without `limit` specified in the parameters:

```
curl -X GET -H "Authorization: ${TOKEN}" 'http://localhost/irods-rest/0.9.3/query?type=general&query=SELECT%20DATA_NAME' | jq .
{
  "error_code": -130000,
  "error_message": "stoi: no conversion"
}
```

with `limit` specified:
```
curl -X GET -H "Authorization: ${TOKEN}" 'http://localhost/irods-rest/0.9.3/query?type=general&query=SELECT%20DATA_NAME&limit=2' | jq .
{
  "_embedded": [],
  "_links": {
    "first": "/irods-rest/0.9.3query?query=SELECT DATA_NAME&limit=2&offset=0&type=general&case-sensitive=1&distinct=1",
    "last": "/irods-rest/0.9.3query?query=SELECT DATA_NAME&limit=2&offset=0&type=general&case-sensitive=1&distinct=1",
    "next": "/irods-rest/0.9.3query?query=SELECT DATA_NAME&limit=2&offset=0&type=general&case-sensitive=1&distinct=1",
    "prev": "/irods-rest/0.9.3query?query=SELECT DATA_NAME&limit=2&offset=0&type=general&case-sensitive=1&distinct=1",
    "self": "/irods-rest/0.9.3query?query=SELECT DATA_NAME&limit=2&offset=2&type=general&case-sensitive=1&distinct=1"
  },
  "count": "0",
  "total": "2"
}
```

**Comment by trel** [comment]
getting the value from the querystring:

https://github.com/irods/irods_client_rest_cpp/blob/0c8c7997519523f6580f5fad5238229d088632e4/irods_specific_implementation/irods_rest_query_api_implementation.h#L35

but when it is not present in the querystring... we see `stoi: no conversion`:

https://github.com/irods/irods_client_rest_cpp/blob/0c8c7997519523f6580f5fad5238229d088632e4/irods_specific_implementation/irods_rest_query_api_implementation.h#L51

is this a correct approach?

```diff
-                uintmax_t query_limit = std::stoi(_query_limit);
+                uintmax_t query_limit{};
+                try {
+                    query_limit = std::stoi(_query_limit);
+                }
+                catch (const std::exception& e) {
+                    query_limit = 100; // set default if bad or not present
+                }
```

**Comment by korydraughn** [comment]
That will most likely work. I think the real issue is why does L35 pass if `limit` is not passed?

The query arguments are provided as optional-like objects. I would expect the second call to `.get` to throw an exception. But, maybe it just returns an empty string instead.

**Comment by trel** [comment]
Right, pretty sure it's returning an empty string - but didn't dig into the Pistache framework that deeply.

**Comment by korydraughn** [comment]
Tou can do is use `.getOrElse("100")` instead of `.get` and then you won't need the try-catch.

**Comment by trel** [comment]
oh, much better.
