### ISSUE TITLE
error in indexed_connection_pool_with_expiry

### ISSUE THREAD

**Issue by mathob** [irods/irods_client_rest_cpp#187]
I would appreciate help with this error when trying to use the rest api on a test system which I'm using to familiarise myself with irods - thanks.

Under Ubuntu 20.04 I have these irods packages installed:

irods-client-rest-cpp/focal,now 0.9.3-0~focal amd64 [installed]
irods-database-plugin-postgres/focal,now 4.3.0-1~focal amd64 [installed]
irods-externals-avro1.11.0-1/focal,now 1.0~focal amd64 [installed,automatic]
irods-externals-boost1.78.0-0/focal,now 1.0~focal amd64 [installed,automatic]
irods-externals-clang-runtime13.0.0-0/focal,now 1.0~focal amd64 [installed,automatic]
irods-externals-fmt8.1.1-0/focal,now 1.0~focal amd64 [installed,automatic]
irods-externals-libarchive3.5.2-0/focal,now 1.0~focal amd64 [installed,automatic]
irods-externals-libs3e4197a5e-0/focal,now 1.0~focal amd64 [installed,automatic]
irods-externals-nanodbc2.13.0-1/focal,now 1.0~focal amd64 [installed,automatic]
irods-externals-zeromq4-14.1.8-0/focal,now 1.0~focal amd64 [installed,automatic]
irods-icommands/focal,now 4.3.0-1~focal amd64 [installed,automatic]
irods-resource-plugin-s3/focal,now 4.3.0.0-1~focal amd64 [installed]
irods-runtime/focal,now 4.3.0-1~focal amd64 [installed,automatic]
irods-server/focal,now 4.3.0-1~focal amd64 [installed]

irods is configured according to installation instructions and appears to be running as expected, with icommands working OK e.g:

~$ ienv
irods_version - 4.3.0
irods_session_environment_file - /home/mathob/.irods/irods_environment.json.3069517
irods_environment_file - /home/mathob/.irods/irods_environment.json
irods_host - localhost
irods_port - 1247
irods_zone_name - tempZone
irods_user_name - rods

~$ ils
Enter your current iRODS password:
/tempZone/home/rods:
  foo.jpg
  hello.txt

The rest services are listening on the appropriate ports:

~$ sudo lsof -i -P -n | grep irods_cli
irods_cli 3038262            root    5u  IPv4 6687259      0t0  TCP *:8087 (LISTEN)
irods_cli 3038263            root    5u  IPv4 6687213      0t0  TCP *:8081 (LISTEN)
irods_cli 3038264            root    5u  IPv4 6687165      0t0  TCP *:8088 (LISTEN)
irods_cli 3038265            root    5u  IPv4 6687188      0t0  TCP *:8082 (LISTEN)
irods_cli 3038266            root    5u  IPv4 6686645      0t0  TCP *:8090 (LISTEN)
irods_cli 3038267            root    5u  IPv4 6687189      0t0  TCP *:8091 (LISTEN)
irods_cli 3038268            root    5u  IPv4 6687246      0t0  TCP *:8089 (LISTEN)
irods_cli 3038269            root    5u  IPv4 6686647      0t0  TCP *:8083 (LISTEN)
irods_cli 3038270            root    5u  IPv4 6687247      0t0  TCP *:8084 (LISTEN)
irods_cli 3038271            root    5u  IPv4 6687271      0t0  TCP *:8085 (LISTEN)
irods_cli 3038272            root    5u  IPv4 6687212      0t0  TCP *:8080 (LISTEN)
irods_cli 3038273            root    5u  IPv4 6687293      0t0  TCP *:8086 (LISTEN)

The nginx reverse proxy is set up and works for the /auth endpoint - so following your README examples I can get a token for user "rods" like this: 

~$ export SECRETS=$(echo -n rods:myrodspassword | base64)

~$ export TOKEN=$(curl -X POST -H "Authorization: Basic ${SECRETS}" http://localhost/irods-rest/0.9.3/auth)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   240  100   240    0     0   1791      0 --:--:-- --:--:-- --:--:--  1791

~$ echo $TOKEN
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXUyJ9.eyJhdWQiOiJhdWRpZW5jZV9jbGFpbSIsImlhdCI6MTY4NzM5ODU1MiwiaXNzIjoiaXNzdWVfY2xhaW0iLCJuYmYiOjE2ODczOTg1NTIsInN1YiI6InN1YmplY3RfY2xhaW0iLCJ1c2VyX25hbWUiOiJyb2RzIn0.-9QCkQE_RbClLPkLxly2WlzLsr8_R2rtgMLzqgLJFiU

However I am unable to use this token with the other endpoints because of some sort of authorization problem. Again following the README example I try to use the authorization token in e.g. a request to the zonereport endpoint, but get this error:

~$ curl -X GET -H "Authorization: ${TOKEN}" 'http://localhost/irods-rest/0.9.3/zonereport'
{"error_code":-904000,"error_message":"iRODS Exception:\n    file: /src/irods_specific_implementation/indexed_connection_pool_with_expiry.hpp\n    function: static void irods::indexed_connection_pool_with_expiry::save_rodsadmin_password_if_necessary()\n    line: 207\n    code: -904000 (ENVIRONMENT_VAR_HOME_NOT_DEFINED)\n    message:\n        Failed to save password for rodsadmin proxy user\nstack trace:\n--------------\n 0# irods::stacktrace::dump() const in /lib/libirods_common.so.4.3.0\n 1# irods::exception::assemble_full_display_what() const in /lib/libirods_common.so.4.3.0\n 2# irods::exception::what() const in /lib/libirods_common.so.4.3.0\n 3# irods::rest::zone_report::operator()(Pistache::Rest::Request const&, Pistache::Http::ResponseWriter&) in /usr/sbin/irods_client_rest_cpp_zonereport_server\n 4# auto irods::rest::handle_request<irods::rest::zone_report>(irods::rest::zone_report&, Pistache::Rest::Request const&, Pistache::Http::ResponseWriter&) in /usr/sbin/irods_client_rest_cpp_zonereport_server\n 5# io::swagger::server::api::ZoneReportApi::handler(Pistache::Rest::Request const&, Pistache::Http::ResponseWriter) in /usr/sbin/irods_client_rest_cpp_zonereport_server\n 6# std::__1::function<Pistache::Rest::Route::Result (Pistache::Rest::Request, Pistache::Http::ResponseWriter)> Pistache::Rest::Routes::bind<void, io::swagger::server::api::ZoneReportApi, Pistache::Rest::Request const&, Pistache::Http::ResponseWriter, io::swagger::server::api::ZoneReportApi*>(void (io::swagger::server::api::ZoneReportApi::*)(Pistache::Rest::Request const&, Pistache::Http::ResponseWriter), io::swagger::server::api::ZoneReportApi*)::'lambda'(Pistache::Rest::Request const&, Pistache::Http::ResponseWriter)::operator()(Pistache::Rest::Request const&, Pistache::Http::ResponseWriter) const in /usr/sbin/irods_client_rest_cpp_zonereport_server\n 7# Pistache::Rest::Route::Result std::__1::__invoke_void_return_wrapper<Pistache::Rest::Route::Result, false>::__call<std::__1::function<Pistache::Rest::Route::Result (Pistache::Rest::Request, Pistache::Http::ResponseWriter)> Pistache::Rest::Routes::bind<void, io::swagger::server::api::ZoneReportApi, Pistache::Rest::Request const&, Pistache::Http::ResponseWriter, io::swagger::server::api::ZoneReportApi*>(void (io::swagger::server::api::ZoneReportApi::*)(Pistache::Rest::Request const&, Pistache::Http::ResponseWriter), io::swagger::server::api::ZoneReportApi*)::'lambda'(Pistache::Rest::Request const&, Pistache::Http::ResponseWriter)&, Pistache::Rest::Request, Pistache::Http::ResponseWriter>(std::__1::function<Pistache::Rest::Route::Result (Pistache::Rest::Request, Pistache::Http::ResponseWriter)> Pistache::Rest::Routes::bind<void, io::swagger::server::api::ZoneReportApi, Pistache::Rest::Request const&, Pistache::Http::ResponseWriter, io::swagger::server::api::ZoneReportApi*>(void (io::swagger::server::api::ZoneReportApi::*)(Pistache::Rest::Request const&, Pistache::Http::ResponseWriter), io::swagger::server::api::ZoneReportApi*)::'lambda'(Pistache::Rest::Request const&, Pistache::Http::ResponseWriter)&, Pistache::Rest::Request&&, Pistache::Http::ResponseWriter&&) in /usr/sbin/irods_client_rest_cpp_zonereport_server\n 8# void Pistache::Rest::Route::invokeHandler<Pistache::Rest::Request, Pistache::Http::ResponseWriter>(Pistache::Rest::Request&&, Pistache::Http::ResponseWriter&&) const in /usr/sbin/irods_client_rest_cpp_zonereport_server\n 9# Pistache::Rest::Router::route(Pistache::Http::Request const&, Pistache::Http::ResponseWriter) in /usr/sbin/irods_client_rest_cpp_zonereport_server\n10# Pistache::Rest::Private::RouterHandler::onRequest(Pistache::Http::Request const&, Pistache::Http::ResponseWriter) in /usr/sbin/irods_client_rest_cpp_zonereport_server\n11# Pistache::Http::Handler::onInput(char const*, unsigned long, std::__1::shared_ptr<Pistache::Tcp::Peer> const&) in /usr/sbin/irods_client_rest_cpp_zonereport_server\n12# Pistache::Tcp::Transport::onReady(Pistache::Aio::FdSet const&) in /usr/sbin/irods_client_rest_cpp_zonereport_server\n13# Pistache::Aio::SyncImpl::handleFds(std::__1::vector<Pistache::Polling::Event, std::__1::allocator<Pistache::Polling::Event> >) const in /usr/sbin/irods_client_rest_cpp_zonereport_server\n14# Pistache::Aio::SyncImpl::runOnce() in /usr/sbin/irods_client_rest_cpp_zonereport_server\n15# Pistache::Aio::SyncImpl::run() in /usr/sbin/irods_client_rest_cpp_zonereport_server\n16# void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, Pistache::Aio::AsyncImpl::Worker::run()::'lambda'()> >(void*) at :?\n17# 0x00007FB94C999609 in /lib/x86_64-linux-gnu/libpthread.so.0\n18# clone in /lib/x86_64-linux-gnu/libc.so.6\n\n"}

**Comment by trel** [comment]
There was a discussion related to this error here:
https://groups.google.com/g/irod-chat/c/4RLqmJtPy20/m/oA7jkQpEAQAJ

Workaround is here...
https://github.com/irods/irods_client_rest_cpp/issues/164#issuecomment-1302300189

**Comment by mathob** [comment]
Brilliant, thanks!

**Comment by trel** [comment]
marking as duplicate of #164
