### ISSUE TITLE
add new `/heartbeat` endpoint

### ISSUE THREAD

**Issue by ganning127** [irods/irods_client_rest_cpp#188]
We aren't able to ping iRODS servers on the frontend for ZMT, so we would like to do it via the CPP API:

**accepts (through query parameters?)** hostname, port

**returns**: `HEARTBEAT` if that hostname / port sent back `HEARTBEAT`, else send back "FAILURE". Or this could be True and False.

**implementation**
1. (simpler, but dirtier) send an HTTP GET request to the hostname / port. if we're able to differentiate INVALID HTTP or NOT FOUND, we can tell that the hostname / port is up. though, this solution will also detect other servers that don't send back HTTP responses as real iRODS servers.
2. (more work, but cleaner, recommended) use TCP sockets to send a [HEARTBEAT message](https://docs.irods.org/4.3.0/system_overview/tips_and_tricks/#monitoring-status-of-irods-servers) to the hostname/port, and see if we get back `HEARTBEAT`.

**Comment by trel** [comment]
Yes, definitely option 2.   don't want to pollute the target iRODS server's logs.

hostname and port as query parameters seem correct

returning `HEARTBEAT` is probably fine for now... but willing to consider more 'standard' things.  what do other APIs send/share when pinging each other's endpoints?

**Comment by ganning127** [comment]
From what I've read, APIs can send a message like "healthy", "warning", "error" or any other string, along with the corresponding HTTP status code when doing a health check.

Before returning "healthy", the API would ping other aspects of its structure (like the database) and make sure that everything is working.

**Comment by trel** [comment]
right - okay - let's just send HEARTBEAT as a response with code 200 and see how it feels/goes.

**Comment by trel** [comment]
This will not be implemented in this repository.

Please see the new HTTP API:

https://github.com/irods/irods_client_http_api
