### ISSUE TITLE
Issue with `/admin` when creating a specific query

### ISSUE THREAD

**Issue by ganning127** [irods/irods_client_rest_cpp#189]
When trying to create a new specific query through `/admin`, I found that the alias `findUsersWithInvalidZones` will sometimes return  `{"error_code":-130000,"error_message":"[json.exception.type_error.316] invalid UTF-8 byte at index 44: 0x68"}`, no matter what the actual specific query content is. 

Though less often than the `json.exception.type_error`, the error message is sometimes  this:
`{"error_code":-130000,"error_message":"iRODS Exception:\n file: /src/irods_specific_implementation/irods_rest_api_base.h\n function: std::string irods::rest::api_base::decode_url(const std::string &) const\n line: 195\n code: -130000 (SYS_INVALID_INPUT_PARAM)\n message:\n Failed to decode URL\nstack trace:\n--------------\n 0# irods::stacktrace::dump() const in /lib/libirods_common.so.4.3.0\n 1# irods::exception::assemble_full_display_what() const in /lib/libirods_common.so.4.3.0\n 2# irods::exception::what() const in /lib/libirods_common.so.4.3.0\n 3# irods::rest::admin::operator()(Pistache::Rest::Request const&, Pistache::Http::ResponseWriter&) in /usr/sbin/irods_client_rest_cpp_admin_server\n 4# auto irods::rest::handle_request(irods::rest::admin&, Pistache::Rest::Request const&, Pistache::Http::ResponseWriter&) in /usr/sbin/irods_client_rest_cpp_admin_server\n 5# io::swagger::server::api::AdminApi::handler(Pistache::Rest::Request const&, Pistache::Http::ResponseWriter) in /usr/sbin/irods_client_rest_cpp_admin_server\n 6# std::__1::function Pistache::Rest::Routes::bind(void (io::swagger::server::api::AdminApi::*)(Pistache::Rest::Request const&, Pistache::Http::ResponseWriter), io::swagger::server::api::AdminApi*)::'lambda'(Pistache::Rest::Request const&, Pistache::Http::ResponseWriter)::operator()(Pistache::Rest::Request const&, Pistache::Http::ResponseWriter) const in /usr/sbin/irods_client_rest_cpp_admin_server\n 7# Pistache::Rest::Route::Result std::__1::__invoke_void_return_wrapper::__call Pistache::Rest::Routes::bind(void (io::swagger::server::api::AdminApi::*)(Pistache::Rest::Request const&, Pistache::Http::ResponseWriter), io::swagger::server::api::AdminApi*)::'lambda'(Pistache::Rest::Request const&, Pistache::Http::ResponseWriter)&, Pistache::Rest::Request, Pistache::Http::ResponseWriter>(std::__1::function Pistache::Rest::Routes::bind(void (io::swagger::server::api::AdminApi::*)(Pistache::Rest::Request const&, Pistache::Http::ResponseWriter), io::swagger::server::api::AdminApi*)::'lambda'(Pistache::Rest::Request const&, Pistache::Http::ResponseWriter)&, Pistache::Rest::Request&&, Pistache::Http::ResponseWriter&&) in /usr/sbin/irods_client_rest_cpp_admin_server\n 8# void Pistache::Rest::Route::invokeHandler(Pistache::Rest::Request&&, Pistache::Http::ResponseWriter&&) const in /usr/sbin/irods_client_rest_cpp_admin_server\n 9# Pistache::Rest::Router::route(Pistache::Http::Request const&, Pistache::Http::ResponseWriter) in /usr/sbin/irods_client_rest_cpp_admin_server\n10# Pistache::Rest::Private::RouterHandler::onRequest(Pistache::Http::Request const&, Pistache::Http::ResponseWriter) in /usr/sbin/irods_client_rest_cpp_admin_server\n11# Pistache::Http::Handler::onInput(char const*, unsigned long, std::__1::shared_ptr const&) in /usr/sbin/irods_client_rest_cpp_admin_server\n12# Pistache::Tcp::Transport::onReady(Pistache::Aio::FdSet const&) in /usr/sbin/irods_client_rest_cpp_admin_server\n13# Pistache::Aio::SyncImpl::handleFds(std::__1::vector >) const in /usr/sbin/irods_client_rest_cpp_admin_server\n14# Pistache::Aio::SyncImpl::runOnce() in /usr/sbin/irods_client_rest_cpp_admin_server\n15# Pistache::Aio::SyncImpl::run() in /usr/sbin/irods_client_rest_cpp_admin_server\n16# 0x0000000000523056 in /usr/sbin/irods_client_rest_cpp_admin_server\n17# 0x00007F001B556609 in /lib/x86_64-linux-gnu/libpthread.so.0\n18# clone in /lib/x86_64-linux-gnu/libc.so.6\n\n"}`

When I change the alias to something like `asdfadsdfasfd` or `usersInvalidZones`, I don't face these errors anymore, even with the same specific query content.

For reference, when an alias is already taken, the error message is `Error on rcGeneralAdmin`. When adding a specific query through `iadmin asq`, `findUsersWithInvalidZones` works fine every time.

**Comment by korydraughn** [comment]
Looks like the error is due to the implementation of `decode_url`.

We need to investigate replacing the implementation with libcurl's decoding facilities.

**Comment by trel** [comment]
This will not be implemented in this repository.

Please see the new HTTP API:

https://github.com/irods/irods_client_http_api
