### ISSUE TITLE
`/admin` not doing URL decoding 

### ISSUE THREAD

**Issue by ganning127** [irods/irods_client_rest_cpp#190]
If we wanted to add the following specific query: `SELECT * FROM R_USER_MAIN`, and we applied `encodeURIComponent()` to it, we would get: `SELECT%20*%20FROM%20R_USER_MAIN`.

When passing this URL encoded string to the REST API, the REST API leaves the `%20` and other codes in there, leaving the specific query with the URL encoded characters.

**Comment by korydraughn** [comment]
Perhaps this is solved by using libcurl's decoding routines.

libcurl is used by the experimental HTTP API project. See https://github.com/irods/irods_client_http_api/blob/723c8b072fa91e2f63d5822355b38ec8eb0b9876/src/common.cpp#L47-L61.

**Comment by trel** [comment]
This will not be implemented in this repository.

Please see the new HTTP API:

https://github.com/irods/irods_client_http_api
