### ISSUE TITLE
Prefer "for (auto&& e : container)" to avoid copies

### ISSUE THREAD

**Issue by korydraughn** [irods/irods_client_rest_cpp#2]
The following line (and many others) will cause a copy to occur.
https://github.com/jasoncoposky/irods_client_rest_cpp/blob/15d367c05e387743d45ed8eb4d5fe9c7c34e4a9f/irods_specific_implementation/irods_rest_query_api_implementation.h#L37

Using `for (auto&& e : container)` covers many if not all type deduction cases and correctly resolves the type. This will avoid copies if references are returned from the underlying iterator.

See https://en.cppreference.com/w/cpp/language/range-for for details.

**Comment by jasoncoposky** [comment]
resolved by commit bdf398e
