### ISSUE TITLE
keyserver

### ISSUE THREAD

**Issue by fh-afk** [irods/irods_client_rest_cpp#45]
The keyserver in install_prerequisites.py does not seem to work. I replaced it with hkp://keyserver.ubuntu.com which does not result in that error.

**Comment by korydraughn** [comment]
I'm guessing you're trying to build externals using the irods/externals repo.

If so, use the changes from the following PR: https://github.com/irods/externals/pull/122

These changes will most likely be merged within a few weeks.

**Comment by trel** [comment]
closing
