### ISSUE TITLE
Investigate conventions around HTTP headers

### ISSUE THREAD

**Issue by korydraughn** [irods/irods_client_rest_cpp#47]
The `x-` HTTP header prefix has been deprecated. See the following links for details:
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers
- https://datatracker.ietf.org/doc/html/rfc6648#page-4

We should introduce a namespace for iRODS specific headers. It should include a space for experimental headers as well.

**Comment by trel** [comment]
This work has been captured in the new HTTP API.

https://github.com/irods/irods_client_http_api
