### ISSUE TITLE
investigate dockerization

### ISSUE THREAD

**Issue by trel** [irods/irods_client_rest_cpp#66]
Would lose the 'ease' of the iRODS configuration... but...

- Will remove the requirement/limitation of installing this software alongside the iRODS Server (in the service account).

- Will allow running concurrent different versions of this REST API at the same time for the same Server/Zone.

- Will allow upgrading for the administrator to separate providing a new REST API version from the requirement of application developers and deployments to change their targeted REST API endpoint.

- Will allow administrators to gracefully announce and deprecate older versions over time.

---

Possible configuration file format...

- needs to also define/configure a JWT signing key (currently using the server's `zone_key` from `server_config.json`).

irods_client_rest_cpp_config.json
```
{
    "irods_client_environment": {
        "zone": "tempZone",
        "host": "<hostname>",
        "port": 1247,
        "ssl_negotiation_policy": "CS_NEG_REFUSE",
        "rodsadmin_username": "<username>",
        "rodsadmin_password": "<password>"
        }
    },
    "rest_api": {
        "irods_rest_cpp_access_server": {
            "port": 8080,
            "threads": 4,
            "maximum_idle_timeout_in_seconds": 10,
            "log_level": "info"
        },
        "irods_rest_cpp_admin_server": {
            "port": 8087,
            "threads": 4,
            "maximum_idle_timeout_in_seconds": 10,
            "log_level": "info"
        },
        "irods_rest_cpp_auth_server": {
            "port": 8081,
            "threads": 4,
            "maximum_idle_timeout_in_seconds": 10,
            "log_level": "info"
        },
        "irods_rest_cpp_get_configuration_server": {
            "port": 8088,
            "threads": 4,
            "maximum_idle_timeout_in_seconds": 10,
            "log_level": "info"
        },
        "irods_rest_cpp_put_configuration_server": {
            "port": 8089,
            "threads": 4,
            "maximum_idle_timeout_in_seconds": 10,
            "log_level": "info"
        },
        "irods_rest_cpp_list_server": {
            "port": 8082,
            "threads": 4,
            "maximum_idle_timeout_in_seconds": 10,
            "log_level": "info"
        },
        "irods_rest_cpp_query_server": {
            "port": 8083,
            "threads": 4,
            "maximum_idle_timeout_in_seconds": 10,
            "log_level": "info"
        },
        "irods_rest_cpp_stream_get_server": {
            "port": 8084,
            "threads": 4,
            "maximum_idle_timeout_in_seconds": 10,
            "log_level": "info"
        },
        "irods_rest_cpp_stream_put_server": {
            "port": 8085,
            "threads": 4,
            "maximum_idle_timeout_in_seconds": 10,
            "log_level": "info"
        },
        "irods_rest_cpp_zone_report_server": {
            "port": 8086,
            "threads": 4,
            "maximum_idle_timeout_in_seconds": 10,
            "log_level": "info"
        }
    }
}
```

**Comment by trel** [comment]
Yes, the current design assumes the REST API is running in the same server... but if `server_config.json` is located in the 'right place'... then yes, I think that would/could work.

I'd be very interested to hear the results of that effort.

With the correct credentials, the REST API just makes client calls into the server, wherever it is defined - so, outside of networking considerations, I believe it will work as expected.

**Comment by trel** [comment]
pull into 0.9.2, and close?

**Comment by alanking** [comment]
The REST client services now run independently of the iRODS server, using the JSON configuration scheme described above (plus a `jwt_signing_key`) and the .irodsA file for authenticating the proxy user. The service can now be run as described in the README in `docker/runner`.

**Comment by trel** [comment]
And we'll plan to remove the requirement on .irodsA and other things as we continue to learn about building clients as a service.
