### ISSUE TITLE
CMakeLists.txt symlink

### ISSUE THREAD

**Issue by SwooshyCueb** [irods/irods_client_rest_cpp#72]
The `CMakeLists.txt` file in the root directory of the repository tree is a symlink to `irods_specific_implementation/CMakeLists.txt`. As far as I can tell, having `CMakeLists.txt` live inside `irods_specific_implementation` serves no purpose, and pointing CMake at `irods_specific_implementation` does not work.

If the symlink and `CMakeLists.txt`'s home in `irods_specific_implementation` has a purpose, it should be documented. Otherwise, the symlink should be removed and `CMakeLists.txt` should be moved to the root of the repository tree.

**Comment by trel** [comment]
I was confused by this as well.    Let's be real boring and make it work at the top level.
